# Generated by Django 2.1.3 on 2019-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190110_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicmenu',
            name='place',
            field=models.ManyToManyField(null=True, to='menu.Place'),
        ),
    ]
